import type { Metadata } from 'next';
import './globals.css';
import { JetBrains_Mono } from 'next/font/google';
import './global';
import ClientLayout from './ClientLayout';

const inter = JetBrains_Mono({
  subsets: ['latin'],
  display: 'swap'
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en' className={inter.className}>
      <body className='antialiased'>
        <ClientLayout>{children}</ClientLayout>
      </body>
    </html>
  );
}
